const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n||0),defaults=['Groceries','Housing','Transport','Dining','Shopping','Bills','Health','Entertainment','Other'];
const config=window.BUDGET_VAULT_CONFIG||{};let db,user,budget=0,categories=[],expenses=[],isRegister=true;
const configured=()=>config.supabaseUrl?.startsWith('https://')&&!config.supabaseAnonKey?.startsWith('PASTE_');
function esc(v){let n=document.createElement('div');n.textContent=v||'';return n.innerHTML}function showError(m){$('#authHint').textContent=m;$('#authHint').style.color='#bf4d58'}
function setAuthMode(reg){isRegister=reg;$('#confirmWrap').hidden=!reg;$('#confirmPasscode').required=reg;$('#authButton').textContent=reg?'Create account':'Log in';$('#authIntro').textContent=reg?'Create a private space to manage your money from any device.':'Welcome back. Log in to access your budget.';$('#passcode').autocomplete=reg?'new-password':'current-password';$('#switchAuth').textContent=reg?'Already have an account? Log in':'New here? Create an account';$('#authHint').textContent=reg?'Use an email address you can access, so you can confirm and recover your account.':'Enter the email address and password you used to register.';$('#authHint').style.color=''}
async function initialise(){if(!configured())return showError('Setup needed: add your Supabase URL and publishable key in config.js.');db=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey);let {data:{session}}=await db.auth.getSession();if(session)await enterApp(session.user)}
async function register(email,password){let {data,error}=await db.auth.signUp({email,password});if(error)throw error;if(!data.session){showError('Account created. Check your email to confirm it, then log in.');setAuthMode(false);return}await enterApp(data.user)}
async function login(email,password){let {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;await enterApp(data.user)}
async function enterApp(next){user=next;$('#auth').hidden=true;$('#dashboard').hidden=false;await loadData()}
async function loadData(){let [br,cr,er]=await Promise.all([db.from('budgets').select('amount').eq('user_id',user.id).maybeSingle(),db.from('categories').select('id,name').order('name'),db.from('expenses').select('id,description,amount,expense_date,notes,category_id,categories(name)').order('expense_date',{ascending:false})]);let bad=[br,cr,er].find(x=>x.error);if(bad)return alert(`Could not load your data: ${bad.error.message}`);budget=Number(br.data?.amount||0);categories=cr.data||[];if(!categories.length){let {data,error}=await db.from('categories').insert(defaults.map(name=>({user_id:user.id,name}))).select('id,name');if(error)return alert(error.message);categories=data}expenses=(er.data||[]).map(x=>({...x,date:x.expense_date,category:x.categories?.name||'Uncategorized'}));render()}
function render(){let spent=expenses.reduce((a,x)=>a+Number(x.amount),0),bal=budget-spent;$('#budgetTotal').textContent=fmt(budget);$('#totalSpent').textContent=fmt(spent);$('#balance').textContent=fmt(bal);$('#balance').style.color=bal<0?'#bf4d58':'';$('#expenseCount').textContent=`${expenses.length} transaction${expenses.length===1?'':'s'}`;$('#budgetState').textContent=budget?(bal<0?'Over budget — review spending':'Remaining after expenses'):'Set a budget to begin';$('#monthLabel').textContent=new Intl.DateTimeFormat('en-IN',{month:'long',year:'numeric'}).format(new Date());$('#expenseCategory').innerHTML=categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');let old=$('#categoryFilter').value;$('#categoryFilter').innerHTML='<option value="">All categories</option>'+categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#categoryFilter').value=old;renderExpenses();renderBreakdown()}
function renderExpenses(){let q=$('#searchInput').value.toLowerCase(),cat=$('#categoryFilter').value,rows=expenses.filter(x=>(!cat||x.category_id===cat)&&(`${x.description} ${x.notes}`.toLowerCase().includes(q)));$('#expensesBody').innerHTML=rows.map(x=>`<tr><td>${new Date(x.date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</td><td><b>${esc(x.description)}</b>${x.notes?`<br><small class="muted">${esc(x.notes)}</small>`:''}</td><td><span class="tag">${esc(x.category)}</span></td><td class="amount">${fmt(x.amount)}</td><td><div class="row-actions"><button onclick="editExpense('${x.id}')">Edit</button><button class="delete" onclick="removeExpense('${x.id}')">Delete</button></div></td></tr>`).join('');$('#emptyState').hidden=!!rows.length}
function renderBreakdown(){let sums={};expenses.forEach(x=>sums[x.category]=(sums[x.category]||0)+Number(x.amount));let max=Math.max(...Object.values(sums),1);$('#categoryBreakdown').innerHTML=Object.keys(sums).length?Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="breakdown-row"><span>${esc(n)}</span><b>${fmt(v)}</b><div class="bar"><i style="width:${v/max*100}%"></i></div></div>`).join(''):'<p class="empty">Category totals will appear here.</p>'}
function openExpense(x){$('#expenseTitle').textContent=x?'Edit expense':'Add expense';$('#expenseId').value=x?.id||'';$('#expenseDescription').value=x?.description||'';$('#expenseAmount').value=x?.amount||'';$('#expenseDate').value=x?.date||new Date().toISOString().slice(0,10);$('#expenseCategory').value=x?.category_id||categories[0]?.id;$('#expenseNotes').value=x?.notes||'';$('#expenseDialog').showModal()}
window.editExpense=id=>openExpense(expenses.find(x=>x.id===id));window.removeExpense=async id=>{if(!confirm('Delete this expense?'))return;let {error}=await db.from('expenses').delete().eq('id',id);if(error)return alert(error.message);await loadData()};function renderCategories(){$('#categoryList').innerHTML=categories.map(c=>`<div><span>${esc(c.name)}</span><button type="button" onclick="removeCategory('${c.id}')">Remove</button></div>`).join('')}window.removeCategory=async id=>{if(expenses.some(x=>x.category_id===id))return alert('Move or delete expenses in this category first.');let {error}=await db.from('categories').delete().eq('id',id);if(error)return alert(error.message);await loadData();renderCategories()};
$('#authForm').onsubmit=async e=>{e.preventDefault();if(!configured())return;let email=$('#username').value.trim(),pass=$('#passcode').value,confirm=$('#confirmPasscode').value;if(isRegister&&pass!==confirm)return showError('Passwords do not match.');try{isRegister?await register(email,pass):await login(email,pass)}catch(e){showError(e.message)}};$('#switchAuth').onclick=()=>setAuthMode(!isRegister);$('#addExpenseBtn').onclick=()=>openExpense();$('#editBudgetBtn').onclick=()=>{$('#budgetInput').value=budget||'';$('#budgetDialog').showModal()};$('#addCategoryBtn').onclick=()=>{renderCategories();$('#categoryDialog').showModal()};document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('#'+x.dataset.close).close());
$('#budgetForm').onsubmit=async e=>{e.preventDefault();let {error}=await db.from('budgets').upsert({user_id:user.id,amount:Number($('#budgetInput').value),updated_at:new Date().toISOString()});if(error)return alert(error.message);$('#budgetDialog').close();await loadData()};$('#expenseForm').onsubmit=async e=>{e.preventDefault();let id=$('#expenseId').value,r={user_id:user.id,description:$('#expenseDescription').value.trim(),amount:Number($('#expenseAmount').value),expense_date:$('#expenseDate').value,category_id:$('#expenseCategory').value,notes:$('#expenseNotes').value.trim()},res=id?await db.from('expenses').update(r).eq('id',id):await db.from('expenses').insert(r);if(res.error)return alert(res.error.message);$('#expenseDialog').close();await loadData()};$('#createCategoryBtn').onclick=async()=>{let name=$('#newCategory').value.trim();if(!name)return;if(categories.some(c=>c.name.toLowerCase()===name.toLowerCase()))return alert('That category already exists.');let {error}=await db.from('categories').insert({user_id:user.id,name});if(error)return alert(error.message);$('#newCategory').value='';await loadData();renderCategories()};
$('#searchInput').oninput=renderExpenses;$('#categoryFilter').onchange=renderExpenses;$('#lockBtn').onclick=async()=>{await db.auth.signOut();user=null;$('#dashboard').hidden=true;$('#auth').hidden=false;$('#username').value=$('#passcode').value=$('#confirmPasscode').value='';setAuthMode(false)};$('#csvBtn').onclick=()=>{let rows=[['Date','Description','Category','Amount','Notes'],...expenses.map(x=>[x.date,x.description,x.category,x.amount,x.notes])],csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='budget-expenses.csv';a.click();URL.revokeObjectURL(a.href)};$('#pdfBtn').onclick=()=>window.print();setAuthMode(true);initialise();
